audit_header: false
title: Washington Real Estate Video Blog with Thai Nguyen
description: >-
  Our mission at The W Group is to be your best resource for Washington real
  estate advice. Whether you are a buyer, seller, or investor, our team of
  professionals can answer any questions you might have about real estate. If
  you are looking to buy or sell a home, you can get all the information and the
  latest updates, tips, and tricks from The The W Group, your professional
  Washington Real Estate Agents.
show_custom_links: true
custom_links:
  - title: Virtual Home Tours
    url: /virtual-home-tours/
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:
client:
  name: Thai Nguyen
  title:
  license_number:
  about_markdown: >-
    The W Group is dedicated to superior service and exceeding expectations;
    with a mission motivated by a passion for people and serving others. Focused
    on creating an elite experience that guarantees you are a valued priority.
    Our innovative marketing style and unwavering commitment to providing value
    through education and technology, is built upon a foundation that offers
    over 14 years of combined industry knowledge and experience. We are inspired
    by a culture that believes success is achieved when we recognize the
    importance of relationships and gratitude for opportunities to make a
    difference in our community. Purposeful in our connections; we are here to
    share visions and achieve goals together.
  brand: The W Group
  brokerage: Compass
  market: Washington
  address: '305 108th Ave NE, Suite 200<br />Bellevue WA 98004-5708'
  phone: (206) 718-0237
  phone_type:
  phone2:
  phone2_type:
  email: thai@thewgroupnw.com
  url: 'https://www.compass.com/agents/thewgroup'
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: /homevalue/
  second_CTA_text: Home Search
  second_CTA_URL: /homesearch/
sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: What’s Your Washington Home Worth?
    CTA_text: >-
      Are you thinking of selling your home or interested in learning about home
      prices in your neighborhood? We can help you.
    CTA_link_text: Free Home Value Report
    CTA_url: /homevalue/
second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: Looking for a Washington Home?
    CTA_text2: Search the entire MLS for your Washington home.
    CTA_link_text2: Search the MLS
    CTA_url2: /homesearch/
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:
socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:
podcast:
  title: Washington Real Estate Podcast with Thai Nguyen
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the Washington
    Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from The W Group - your professional
    Washington Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in Washington, home
    selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: Thai Nguyen
images:
  client_headshot_path: /img/headshot.jpg
  client_headshot_path2: /img/headshot2.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Washington Real Estate Video Blog
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg
site_colors:
  brand_color: '#000000'
  theme_color: '#000000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#000000'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: 'rgba(0, 0, 0, 0)'
  button_text_color: '#000000'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'